[project]
name = "grab"
version = "0.1.0"
description = "AI-Powered Email Management"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mypy>=1.15.0",
]

[tool.distutils.egg_info]
egg_base = "."

[tool.setuptools]
packages = ["grab"]